# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    runs-on: macos-14

    strategy:
      matrix:
        xcode: 
        - "16.0"

    steps:
    - uses: actions/checkout@v3
    
    - name: Xcode Select ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_16.0.app

    - name: Get swift version
      run: swift --version # Swift 6.0

    - name: SPM Cache ${{ matrix.xcode }}
      uses: actions/cache@v3.2.6
      with:
        path: .build
        key: ${{ runner.os }}-${{ matrix.xcode }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.xcode }}-spm-
      
    - name: Build ${{ matrix.xcode }}
      run: swift build -v
      
    - name: Run tests ${{ matrix.xcode }}
      run: swift test -v 2>&1 | xcpretty
